spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_marketplace
spring.datasource.username=postgres
spring.datasource.password=snehith

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082

razorpay.key.id=rzp_test_T2JJ200mpmbbVJ
razorpay.key.secret=MZPsSpwbPDcFAbfwS6dS0yy5